# Generated by Django 4.1.4 on 2022-12-07 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Disciplina",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=40)),
                ("link", models.CharField(max_length=300)),
                ("quantidade", models.CharField(max_length=300)),
                (
                    "disciplina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="card.disciplina",
                    ),
                ),
            ],
        ),
    ]
