# Generated by Django 4.1.4 on 2022-12-07 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("card", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="quantidade",
            field=models.SmallIntegerField(),
        ),
    ]
